<?php
session_start();
if (!isset($_SESSION['id'])) {
    header("Location: ../login.php");
    exit();
}

include '../mypbra_connect.php';
error_reporting(E_ALL);
ini_set('display_errors', 1);

$id = $_SESSION['id'];

// Admin check
$is_admin = false;
$stmt = $conn->prepare("SELECT user_type FROM users WHERE id = ?");
$stmt->bind_param("i", $id);
$stmt->execute();
$stmt->bind_result($user_type);
if ($stmt->fetch() && $user_type === 'admin') {
    $is_admin = true;
}
$stmt->close();

// Handle announcement POST
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $title = $_POST['title'] ?? '';
    $content = $_POST['content'] ?? '';
    $imagePath = null;

    // Handle image upload
    if (!empty($_FILES['image']['name'])) {
        $imageTmp = $_FILES['image']['tmp_name'];
        $imageName = basename($_FILES['image']['name']);
        $uploadDir = '../uploads/announcements/';
        if (!is_dir($uploadDir)) {
            mkdir($uploadDir, 0777, true);
        }
        $uniqueName = uniqid() . '_' . $imageName;
        $fullPath = $uploadDir . $uniqueName;
        move_uploaded_file($imageTmp, $fullPath);
        $imagePath = 'uploads/announcements/' . $uniqueName; // ✅ Use this for HTML src
    }

    // Save to database
    if (!empty($title) && !empty($content)) {
        $stmt = $conn->prepare("INSERT INTO announcement (title, content, image_path, created_at) VALUES (?, ?, ?, NOW())");
        $stmt->bind_param("sss", $title, $content, $imagePath);
        $stmt->execute();
        $stmt->close();

        header("Location: " . $_SERVER['PHP_SELF']);
        exit();
    }
}

// Fetch announcements (latest first)
$sql = "SELECT * FROM announcement ORDER BY created_at DESC";
$result = $conn->query($sql);
if (!$result) {
    die("Query failed: " . $conn->error);
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" href="homepage.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <script src="homepage.js"></script>
</head>

<body onload="fetchNotifications()">
    <header>
        <?php include '../includes/navbar.php'; ?>
    </header>

    <div class="content-body">
        <!-- Add the new two-column layout here -->
        <div class="top-content">
            <!-- Left Column - Calendar -->
            <div class="calendar-section">
                <div class="calendar-widget">
                    <h3>Calendar</h3>
                    <div class="calendar-header">
                        <div class="calendar-controls">
                            <button class="nav-btn" onclick="prevMonth()"><i class="fas fa-chevron-left"></i></button>
                            <span id="currentMonth">August 2025</span>
                            <button class="nav-btn" onclick="nextMonth()"><i class="fas fa-chevron-right"></i></button>
                        </div>
                    </div>

                    <button class="new-event-btn">
                        <i class="fas fa-plus"></i> New Event
                    </button>

                    <div class="calendar-grid" id="calendarGrid">
                        <!-- Calendar will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Right Column - Announcements -->
            <div class="announcement-section">
                <?php include '../includes/announcement.php'; ?>
            </div>
        </div>

        <div class="feature-container">
            <div class="role-container" onclick="window.location.href='../roles/roles.php';">
                <div class="text-role">
                    <h2><strong>ROLE</strong></h2>
                    <p>This section lets you easily keep track of all your roles, including when they start, end, and
                        the latest tasks completed.</p>
                </div>
            </div>

            <div class="pbstaff-container" onclick="window.location.href='../staff/staffsch.php';">
                <div class="text">
                    <h2><strong>PB STAFF</strong></h2>
                    <p>Get to know who is in charge of each department and all of its staff.</p>
                </div>
            </div>
        </div>

        <div class="setting-section">
            <div class="feedback" onclick="window.location.href='../feedback/feedback.php';">
                <i class="fas fa-comment"></i> Feedback
            </div>
            <div class="report" onclick="window.location.href='../report/report.php';">
                <i class="fas fa-clipboard"></i> Report
            </div>
            <div class="user-support" onclick="window.location.href='../usersupport/usersupport.php';">
                <i class="fas fa-question-circle"></i> User Support
            </div>

        </div>

    </div>


    <footer>
        <p>&copy; 2025 Politeknik Brunei Role Appointment (PbRA). All rights reserved.</p>
    </footer>

</body>

</html>